[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]

[tool.uv]
requires-python = ">=3.11"

[tool.uv.scripts]
start = "uvicorn main:app --reload"
